apiVersion: apps/v1
kind: Deployment
metadata:
  name: response-back
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-running.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argocd
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: response-back
  template:
    metadata:
      labels:
        app: response-back
    spec:
      # initContainers:
      #   - name: wait-for-surveydocument
      #     image: busybox
      #     command: ['sh', '-c', 'until ping surveydocument-service; do echo waiting for surveydocument; sleep 2; done;']
      containers:
        - name: response-back
          image: kjk7212/response-back:17
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: response-back-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: response-back
