apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-back
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-running.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argocd
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: survey-back
  template:
    metadata:
      labels:
        app: survey-back
    spec:
      # initContainers:
      #   - name: wait-for-mysql
      #     image: busybox
      #     command: ['sh', '-c', 'until nslookup mysql:3306; do echo waiting for myweb-mysql; sleep 2; done;'] 
      containers:
        - name: survey-back
          image: kjk7212/survey-back:55
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: spring
            - containerPort: 8082
              name: spring-actuator
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: survey-back-service
  labels:
    app: survey-back-service
spec:
  ports:
    - name: spring
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: spring-actuator
      port: 8082 # service의 port
      targetPort: 8082 # pod의 target port
      protocol: TCP
  selector:
    app: survey-back
