apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-back
  template:
    metadata:
      labels:
        app: user-back
    spec:
      # initContainers:
      #   - name: wait-for-surveyanswer
      #     image: busybox
      #     command: ['sh', '-c', 'until nslookup surveyanswer-service; do echo waiting for surveyanswer; sleep 2; done;']
      containers:
        - name: user-back
          image: kjk7212/user-back:3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: user-back-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: user-back
